mesh:
  type: rectangle
  nx: 64
  ny: 64
model:
  coulomb_fac_enabled: False
  do_streamline_upwinding: True
  is_isothermal: True
  n_init: 2.0e+12
  S0n_fac: 0.03
  S0T_fac: 0.03
  T_init: 6.0e-6
physical:
  n_0: 2.0e+18
  nu: 0.03
  omega_ci: 9.6e+5
  R: 0.5
  T_e0: 6
time:
  num_steps: 400
  output_freq: 1
  t_end: 1000.0e-6
