mesh:
  type: rectangle
  nx: 64
  ny: 64
model:
  do_streamline_upwinding: True
  n_init: 2.0e+14
  S0n_fac: 0.03
  S0T_fac: 0.03
  T_init: 6.0e-4
physical:
  n_0: 2.0e+18
  nu: 0.03
  omega_ci: 9.6e+5
  R: 0.5
  T_e0: 6
time:
  num_steps: 500000
  info_freq: 100
  output_freq: 1000
  t_end: 500.0e-6
