mesh:
  type: cuboid
  nx: 64
  ny: 64
  nz: 4
model:
  is_isothermal: True
  S0n_fac: 0.03
  S0T_fac: 0.03
physical:
  Lz: 18.0
  n_0: 2.0e+18
  nu: 0.03
  omega_ci: 9.6e+5
  R: 0.5
  T_e0: 6
time:
  num_steps: 1000
  output_freq: 10
  start: 0.0
  end: 10.0
